# -*- coding: utf-8 -*-
"""Generated by ArcGIS ModelBuilder on: 2019-10-15 14:25:17
All ModelBuilder functionality may not be exported. Edits may be required for equivalency with the original model.
"""

import arcpy

# To allow overwriting the outputs change the overwrite option to true.
arcpy.env.overwriteOutput = False

# Script parameters
Jeopardy_CSV_File = arcpy.GetParameterAsText(0) or r"C:\Users\whitacrej\Documents\GitHub\Python-For-ArcGIS-2019\ExerciseData\CSV\JeopardyContestants_LatLon.csv"
# Local variables:
JeopardyContestants_Table = r"C:\Users\whitacrej\Documents\GitHub\Python-For-ArcGIS-2019\ExerciseData\Illinois.gdb\JeopardyContestants_Table"
Jeopardy_Contestants = "Jeopardy Contestants"
Jeopardy_Contestants_Feature_Class_Output = r"C:\Users\whitacrej\Documents\GitHub\Python-For-ArcGIS-2019\ExerciseData\Illinois.gdb\JeopardyContestants"
Jeopardy_Contestants_Buffer_Output = r"C:\Users\whitacrej\Documents\GitHub\Python-For-ArcGIS-2019\ExerciseData\Illinois.gdb\JeopardyContestants_Buffer"

# Process: Copy Rows
arcpy.CopyRows_management(in_rows=Jeopardy_CSV_File, out_table=JeopardyContestants_Table, config_keyword="")

# Process: Make XY Event Layer
arcpy.MakeXYEventLayer_management(table=JeopardyContestants_Table, in_x_field="lon", in_y_field="lat", out_layer=Jeopardy_Contestants, spatial_reference="GEOGCS['GCS_WGS_1984',DATUM['D_WGS_1984',SPHEROID['WGS_1984',6378137.0,298.257223563]],PRIMEM['Greenwich',0.0],UNIT['Degree',0.0174532925199433]];-400 -400 1000000000;-100000 10000;-100000 10000;8.98315284119521E-09;0.001;0.001;IsHighPrecision", in_z_field="")

# Process: Select
arcpy.Select_analysis(in_features=Jeopardy_Contestants, out_feature_class=Jeopardy_Contestants_Feature_Class_Output, where_clause=""lat" IS NOT NULL OR "lon" IS NOT NULL")

# Process: Buffer
arcpy.Buffer_analysis(in_features=Jeopardy_Contestants_Feature_Class_Output, out_feature_class=Jeopardy_Contestants_Buffer_Output, buffer_distance_or_field="5 Miles", line_side="FULL", line_end_type="ROUND", dissolve_option="NONE", dissolve_field="", method="GEODESIC")

